- name: damask_parse_env
  setup: |
    source /full/path/to/.venv/bin/activate
  executables:
  - label: python_script
    instances:
    - command: python "<<script_path>>" <<args>>
      num_cores:
        start: 1
        stop: 32
      parallel_mode: null

- name: formable_env
  setup: |
    source /full/path/to/.venv/bin/activate
  executables:
  - label: python_script
    instances:
    - command: python "<<script_path>>" <<args>>
      num_cores:
        start: 1
        stop: 32
      parallel_mode: null

- name: defdap_env
  setup: |
    source /full/path/to/.venv/bin/activate
  executables:
  - label: python_script
    instances:
    - command: python "<<script_path>>" <<args>>
      num_cores:
        start: 1
        stop: 32
      parallel_mode: null

- name: damask_env
  setup: |
    module load mpi/intel-18.0/openmpi/4.1.0
    IMG_PATH=/full/path/to/DAMASK-docker-images/damask-grid_3.0.0-alpha7.sif
    export HDF5_USE_FILE_LOCKING=FALSE
  executables:
  - label: damask_grid
    instances:
    - command: singularity run $IMG_PATH
      num_cores: 1
      parallel_mode: null
    - command: mpirun -n $NSLOTS singularity run $IMG_PATH
      num_cores:
        start: 2
        stop: 32
      parallel_mode: null

- name: matlab_env
  setup: |
    module load apps/binapps/matlab/R2019a
    module load apps/binapps/matlab/third-party-toolboxes/mtex/5.3
  executables:
  - label: compile_mtex
    instances:
    - command: compile-mtex <<script_name>> <<args>>
      num_cores: 1
      parallel_mode: null

  - label: run_compiled_mtex
    instances:
    - command: ./run_<<script_name>>.sh $MATLAB_HOME <<args>>
      num_cores: 1
      parallel_mode: null

  - label: run_mtex
    instances:
    - command: matlab -singleCompThread -batch "<<script_name_no_ext>> <<args>>"
      num_cores: 1
      parallel_mode: null

- name: python_env
  executables:
  - label: python_script
    instances:
    - command: python "<<script_path>>" <<args>>
      num_cores:
        start: 1
        stop: 32
      parallel_mode: null

- name: dream_3D_env
  executables:
  - label: dream_3D_runner
    instances:
    - command: /full/path/to/dream3d/DREAM3D-6.5.171-Linux-x86_64/bin/PipelineRunner
      num_cores: 1
      parallel_mode: null
  - label: python_script
    instances:
    - command: python "<<script_path>>" <<args>>
      num_cores: 1
      parallel_mode: null
