name: Test demo workflows

on:
  workflow_dispatch: # manual invocation

jobs:
  # cache-app-data:
  #   permissions:
  #     # No write permission
  #     contents: read
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v6
  #       with:
  #         ref: ${{ inputs.ref }}

  #     - name: Set up python
  #       uses: actions/setup-python@v6
  #       with:
  #         python-version: "3.13"

  #     - name: Set up poetry
  #       uses: hpcflow/github-support/setup-poetry@main
  #       timeout-minutes: ${{ inputs.install-poetry-timeout-minutes }}
  #       with:
  #         version: ${{ inputs.poetry-version }}

  #     - name: Cache dependencies
  #       uses: hpcflow/github-support/init-cache@main
  #       with:
  #         name: test
  #         version: "3.13"

  #     - name: Install dependencies
  #       timeout-minutes: ${{ inputs.install-timeout-minutes }}
  #       run: |
  #         poetry install --without dev,pyinstaller

  #     - name: Cache all app data and programs
  #       run: |
  #         poetry run python -m ${{ inputs.CLI_module }} manage cache-all

  #     - name: Upload all cached app data/programs
  #       id: upload-cached-app-data
  #       uses: actions/upload-artifact@v6
  #       with:
  #         name: ${{ inputs.executable_name }}-app-data-cache
  #         path: ~/.cache/${{ inputs.executable_name }}

  test-demo-workflows:
    # needs: [cache-app-data]
    permissions:
      # No write permission
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      # - name: Download prepared cached app data
      #   uses: actions/download-artifact@v7
      #   with:
      #     name: ${{ inputs.executable_name }}-app-data-cache
      #     path: ${{ inputs.executable_name }}-app-data-cache

      - name: Set up poetry
        uses: hpcflow/github-support/setup-poetry@main
        timeout-minutes: ${{ inputs.install-poetry-timeout-minutes }}
        with:
          version: ${{ inputs.poetry-version }}

      - name: Cache dependencies
        uses: hpcflow/github-support/init-cache@main
        with:
          name: test
          version: ${{ matrix.python-version }}

      - name: Install dependencies
        timeout-minutes: ${{ inputs.install-timeout-minutes }}
        run: |
          poetry install --without dev,pyinstaller

      - name: Install necessary MatFlow environments
        id: configure_envs
        run: |
          poetry run ${{ inputs.executable_name }} env setup python-all --use-current
          poetry run ${{ inputs.executable_name }} env setup damask --docker-image damaskmultiphysics/damask-grid:3.0.2
          result=$(poetry run ${{ inputs.executable_name }} env info source_file -l python)
          echo "env_source_file=$result" >> "$GITHUB_OUTPUT"

      # - name: Install cached app data
      #   env:
      #     PYTHONUTF8: 1
      #   run: |
      #     poetry run ${{ inputs.executable_name }} data install-cache ${{ inputs.executable_name }}-app-data-cache/data
      #     poetry run ${{ inputs.executable_name }} data --list
      #     poetry run ${{ inputs.executable_name }} program install-cache ${{ inputs.executable_name }}-app-data-cache/programs          
      #     poetry run ${{ inputs.executable_name }} program --list

      - name: Run demo workflows       
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHONUNBUFFERED: ok
        run: |
          poetry run ${{ inputs.executable_name }} test --with-env-source ${{ steps.configure_envs.outputs.env_source_file }} --demo-workflows
