name: Test demo workflows

on:
  workflow_dispatch: # manual invocation
    inputs:
      pytest_args:
        required: false
        type: string
        description: Extra arguments to pass to pytest.
        default: ""
      poetry-version:
        required: false
        type: string
        description: Version of Poetry.
        default: "2.1.3"
      python-version:
        required: false
        type: string
        description: Version of Python.
        default: "3.13"        
jobs:
  # cache-app-data:
  #   permissions:
  #     # No write permission
  #     contents: read
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v6
  #       with:
  #         ref: ${{ inputs.ref }}

  #     - name: Set up python
  #       uses: actions/setup-python@v6
  #       with:
  #         python-version: "3.13"

  #     - name: Set up poetry
  #       uses: hpcflow/github-support/setup-poetry@main
  #       timeout-minutes: ${{ inputs.install-poetry-timeout-minutes }}
  #       with:
  #         version: ${{ inputs.poetry-version }}

  #     - name: Cache dependencies
  #       uses: hpcflow/github-support/init-cache@main
  #       with:
  #         name: test
  #         version: "3.13"

  #     - name: Install dependencies
  #       timeout-minutes: ${{ inputs.install-timeout-minutes }}
  #       run: |
  #         poetry install --without dev,pyinstaller

  #     - name: Cache all app data and programs
  #       run: |
  #         poetry run python -m ${{ inputs.CLI_module }} manage cache-all

  #     - name: Upload all cached app data/programs
  #       id: upload-cached-app-data
  #       uses: actions/upload-artifact@v6
  #       with:
  #         name: matflow-app-data-cache
  #         path: ~/.cache/matflow

  test-demo-workflows:
    # needs: [cache-app-data]
    permissions:
      # No write permission
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - name: Set up python ${{ inputs.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      # - name: Download prepared cached app data
      #   uses: actions/download-artifact@v7
      #   with:
      #     name: matflow-app-data-cache
      #     path: matflow-app-data-cache

      - name: Set up poetry
        uses: hpcflow/github-support/setup-poetry@main
        with:
          version: ${{ inputs.poetry-version }}

      - name: Cache dependencies
        uses: hpcflow/github-support/init-cache@main
        with:
          name: test
          version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          poetry install --without dev,pyinstaller

      - name: Install necessary pip packages
        run: |
          poetry run pip install damask-parse

      - name: Install necessary MatFlow environments
        id: configure_envs
        run: |
          poetry run matflow env setup python-all --use-current
          poetry run matflow env setup damask --docker-image damaskmultiphysics/damask-grid:3.0.2
          result=$(poetry run matflow env info source_file -n python_env)
          echo "env_source_file=$result" >> "$GITHUB_OUTPUT"

      # - name: Install cached app data
      #   env:
      #     PYTHONUTF8: 1
      #   run: |
      #     poetry run matflow data install-cache matflow-app-data-cache/data
      #     poetry run matflow data --list
      #     poetry run matflow program install-cache matflow-app-data-cache/programs          
      #     poetry run matflow program --list

      - name: Run demo workflows       
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHONUNBUFFERED: ok
        run: |
          poetry run matflow test --with-env-source ${{ steps.configure_envs.outputs.env_source_file }} --demo-workflows

      - name: Upload all pytest temp dirs
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: pytest-temp
          path: /tmp/pytest-of-*
